/*
 * Moteur.java
 *
 * Created on 26 décembre 2007, 21:52
 */

package netbiodyn;// Creation of a package, this line indicating that the actual file will be in this package


/**
 *
 * @author  user
 */

public class Moteur extends ProtoBioDyn {
    
    //Initialization of a new Moteur object
    public Moteur() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
    }
    
}
